extends: "spectral:oas"
rules:
  info-contract: error
  operation_tags: error
  tags-should-have-description:
    description: Tags must have a description
    given: $.tags[*]
    severity: error
    then:
      field: description
      function: truthy